module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  arrowParens: 'always',
  proseWrap: 'preserve',
  endOfLine: 'auto',
  parser: 'babel',
  bracketSameLine: false,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  trimTrailingWhitespace: true,
  overflow: 'auto',
  ignorePath: [
    '**/node_modules/**',
    '**/coverage/**',
    '**/dist/**',
    '.prettierignore',
    '.eslintignore',
    '.gitignore',
  ],
};
